master_data_model:
  outputs:
    dev:
      dataset: "{{ env_var('dataset') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('dbt_keyfile') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('project') }}"
      threads: 4
      type: bigquery
  target: dev